### ISSUE TITLE
100% CPU and lots of logs when setting a range 6-7 in days

### ISSUE THREAD

**Issue by ThomasChiroux** [aptible/supercronic#63] opened 2020-05-07 19:10 UTC
ex this simple job:
```
45 4        *  *  6-7   echo "foo"
```

generates hundreds logs per seconds of:

```
time="2020-05-07T20:55:58+02:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-05-07T20:55:58+02:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-05-07T20:55:58+02:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-05-07T20:55:58+02:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
...
```

same job with either:

```
45 4        *  *  6,7   echo "foo"
```
or
```
45 4        *  *  6,0   echo "foo"
```
or

```
45 4        *  *  6   echo "foo"
45 4        *  *  7   echo "foo"
```

are working normally, so a work-around is pretty straightforward.

I know "7" is non standard, but since it's supported alone and within lists, I suppose it should be supported in range.
(and taking 100% of cpu for logging warning is not good anyway)

Thanks,
Regards,
Thomas.

**Comment by hartwork** [comment] 2020-11-13 21:13
Conforming the bug for latest Git `master` at 76cc5fb33cedfa1bf3520a01d26a60ba71c238b6.

Here's one way to reproduce it without putting your system on 100% load for longer:
```console
# go build . && timeout -s 9 1 ./supercronic -debug <(echo '45 4        *  *  6-7   echo "foo"') |& head
time="2020-11-13T22:11:15+01:00" level=info msg="read crontab: /dev/fd/63"
time="2020-11-13T22:11:15+01:00" level=debug msg="try parse(6): 45 4        *  *  6-7   echo \"foo\"[0:28] = 45 4        *  *  6-7   echo"
time="2020-11-13T22:11:15+01:00" level=debug msg="try parse(5): 45 4        *  *  6-7   echo \"foo\"[0:21] = 45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=debug msg="job will run next at 0001-01-01 00:00:00 +0000 UTC" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=debug msg="job will run next at 0001-01-01 00:00:00 +0000 UTC" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=debug msg="job will run next at 0001-01-01 00:00:00 +0000 UTC" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=warning msg="job took too long to run: it should have started -2562047h47m16.854775808s ago" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
time="2020-11-13T22:11:15+01:00" level=debug msg="job will run next at 0001-01-01 00:00:00 +0000 UTC" job.command="echo \"foo\"" job.position=0 job.schedule="45 4        *  *  6-7"
```

**Comment by hartwork** [comment] 2020-11-13 22:15
Here's what I found at a first closer look under the hood:
supercronic offloads parsing the crontab line to https://github.com/krallin/cronexpr at https://github.com/aptible/supercronic/blob/61a65736ffd044af0bcae2236dbd8d86ab83a5ed/crontab/crontab.go#L40 . The code of `ParseStrict` has not been merged into `master` but sits on top of a branch named `strict` at https://github.com/krallin/cronexpr/commits/strict . Now that function produces an `Expression` https://github.com/gorhill/cronexpr/blob/88b0669f7d75f171bd612b874e52b95c190218df/cronexpr.go#L28-L45 with the structured result of the parse.

In `Expression`, two internal fields deserve attention in context of this ticket:

- field `daysOfWeek` and
- field `daysOfWeekRestricted`.

If we now parse the crontab lines…

- `45 4 * * 0,6 echo "foo"`
- `45 4 * * * echo "foo"`
- `45 4 * * 6-7 echo "foo"`

…we get…

- Syntax `0,6`
  - `.daysOfWeek` is `[0:true 6:true]`
  - `.daysOfWeekRestricted` is `true`
- Syntax `*`
  - `.daysOfWeek` is `[]`
  - `.daysOfWeekRestricted` is `false`
- Syntax `6-7`
  - `.daysOfWeek` is `[]`
  - `.daysOfWeekRestricted` is `true`

…respectively for those two fields. Note how for the last case with day of the week `6-7` the result is a weird mix of the other too. So that's where things start to get out of control.

The original https://github.com/gorhill/cronexpr has been marked as archived so this seems to need a fix in @krallin's fork  https://github.com/krallin/cronexpr but it lacks an issue tracker. @krallin what would be the best way to go forward here?

**Comment by krallin** [comment] 2020-11-14 14:56
Thanks for the report & the investigation! I sent #78 to reject such expressions. It'd be nice to try and support them, but I think that would require substantial changes to cronexpr, so for now given the availability of a trivial workaround, that seems like the better approach.

**Comment by hartwork** [comment] 2020-11-14 15:15
I agree that rejecting syntax `6-7` might be an economical approach to address the problem. I don't support depending on (1) a repository with no issue tracker and (2) commits on a branch other than `master` though. If you don't want to shoulder cronexpr that package yourself, okay, but where can it be moved with more shoulders then? The current situation is not ideal.

**Closed** 2020-11-14 16:39 UTC

**Comment by krallin** [comment] 2020-11-14 17:01
@hartwork,

First off, let me start by mentioning I found your last comment unnecessarily accusatory and demeaning, and full of entitlement. With all due respect, going to someone (i.e. me) who's giving you software for free (i.e. Supercronic) and telling them you don't support what they're doing and that their work isn't ideal is perhaps not a great way to start a conversation.

Now, I'm going to assume good intentions here and assume you didn't mean it that way, but I won't entertain the conversation longer if that continues.

---

I think you might not realize that for all intents and purposes, this repository is *a part of Supercronic*, and is maintained all the same as Supercronic. That branch you found exists exclusively to provide what Supercronic needs, and Supercronic is the only user of it that I'm aware of. Also note that while those commits aren't on master, Supercronic depends on a fixed *commit* (i.e. not a branch).

The reason Supercronic depends on said fork is simply historical. Indeed, `cronexpr` wasn't archived when Supercronic started, so we forked it and made the changes we needed, with the intention that we could switch back to the original package once our changes were merged. That never happened, and cronexpr was archived, and as a result those changes were never merged. What wasn't broken didn't need fixing, so we just stuck with the fork: it's as simple as that.

In any case, I sent #79 to just merge cronexpr into Supercronic, since the future where we switch back to upstream cronexpr will presumably never materialize given that the package has been abandoned. However, note that making this change is purely an administrative tweak that I'm making it for the sake of convenience and to avoid confusion. Notably, it doesn't mean that our fork of cronexpr will suddenly become more or less maintained than it already was.

---

As an aside, if you do think Supercronic should support 6-7 as a day range, that might be a fair feature request. That said, Supercronic has gone on for years without supporting this, so I'm not seeing a lot of urgency towards making this work.

**Comment by hartwork** [comment] 2020-11-14 17:43
> @hartwork,
> 
> First off, let me start by mentioning I found your last comment unnecessarily accusatory and demeaning, and full of entitlement. With all due respect, going to someone (i.e. me) who's giving you software for free (i.e. Supercronic) and telling them you don't support what they're doing and that their work isn't ideal is perhaps not a great way to start a conversation.
> 
> Now, I'm going to assume good intentions here and assume you didn't mean it that way, but I won't entertain the conversation longer if that continues.

Hi @krallin,

I should have picked better words than "I do not support" as your reaction shows, I agree.  It was 100% not personal, you're doing great work in general as to what I can see.  I'm not an English native speaker and I wanted to be clear about how "wrong" that hidden code fork approach is best practice book.  Maybe I missed a language nuance.
I should add though that our discussion started months ago, not today, with no reply for months at #75 and no reply for months more at #63.  Being an active part of the software libre movement myself, I find that the picture of you giving me software for free is incomplete. 

> The reason Supercronic depends on said fork is simply historical. Indeed, `cronexpr` wasn't archived when Supercronic started, so we forked it and made the changes we needed, with the intention that we could switch back to the original package once our changes were merged. That never happened, and cronexpr was archived, and as a result those changes were never merged. What wasn't broken didn't need fixing, so we just stuck with the fork: it's as simple as that.

That picture is missing the move in #78 which communicate sticking to the hidden code situation to me, and which was the reason I decided to speak up about it, before #79 was online to have a chance at adjusting that impression. I picked insensitive tone as proven, okay, but I did have a point.

> As an aside, if you do think Supercronic should support 6-7 as a day range, that might be a fair feature request. That said, Supercronic has gone on for years without supporting this, so I'm not seeing a lot of urgency towards making this work.

I don't mind too much one way or the other.  I cared about fixing a long-unfixed bug in a software with users, mostly.

**Comment by krallin** [comment] 2020-11-14 17:55
> I should have picked better words than "I do not support" as your reaction shows, I agree. It was 100% not personal, you're doing great work in general as to what I can see. I'm not an English native speaker and I wanted to be clear about how "wrong" that hidden code fork approach is best practice book. Maybe I missed a language nuance.

That's fair, thanks for acknowledging that :)

> I should add though that our discussion started months ago, not today, with no reply for months at #75 and no reply for months more at #63. Being an active part of the software libre movement myself, I find that the picture of you giving me software for free is incomplete.

That's reasonable. I definitely haven't had too much time to spend on this, and to be entirely honest, I simply missed / forgotten about #63 (as for #75, I didn't really have the energy to really do much about it, since I suspected we might end up having the conversation we're now having today :) ).

> That picture is missing the move in #78 which communicated sticking to the hidden code situation to me, and which was the reason I decided to speak up about it, before #79 was online to have a chance at adjusting that impression.

I think you're perhaps reading into that a little bit more than there really is (which, to be clear, is understandable). I didn't make a conscious decision to stick to the current approach in that PR: I just didn't think about revisiting it. 

>  I picked insensitive tone as proven, okay, but I did have a point.

That's fair, I agree that the way the code is setup currently is a little confusing, and while I think it was reasonable from a "we'll do this until we can get this merged upstream" standpoint, I agree that it's no longer appropriate years later.

> I cared about fixing a long-unfixed bug in a software with users, mostly.

I appreciate that; thanks! Your investigation absolutely made it easier to fix the bug (and also ... reminded me to look into it!)

---

Anyhow, it sounds like we're on the same page now:

- If I understand correctly, #79 is something we are both happy with (let me know if not?)
- Thanks for acknowledging what I mentioned with regard to the tone :)
- And, finally, as I mentioned, thanks for your help fixing the `6-7` parsing issue at hand in this thread!

**Comment by hartwork** [comment] 2020-11-14 19:37
I'm glad you're taking my reply well, cool! With regard to #79 I think it is an improvement and the way it's done preserving the original Git history seems like a good clean choice. Let me comment over there with one small finding for consideration.
